# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 08:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jeju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_logo', models.FileField(upload_to='files/%Y%m%d/')),
                ('corp_descriptioin', models.TextField()),
                ('corp_location', models.TextField(max_length=200)),
                ('corp_coordinates', models.CharField(max_length=50)),
                ('usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(default='null', max_length=32, verbose_name='APIkey')),
                ('file', models.CharField(default='null', max_length=100, verbose_name='파일이름')),
                ('regdate', models.DateTimeField(default=datetime.date.today, verbose_name='등록일시')),
                ('update', models.DateTimeField(default=datetime.date.today, verbose_name='갱신일시')),
                ('logcnt', models.IntegerField(default=0, verbose_name='등록로그수')),
                ('usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='foods',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='file4',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='file5',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='issell',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='rinfo',
        ),
        migrations.AddField(
            model_name='foods',
            name='apikey',
            field=models.CharField(default='null', max_length=200, verbose_name='고유키'),
        ),
        migrations.AddField(
            model_name='foods',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='할인율'),
        ),
        migrations.AddField(
            model_name='reply',
            name='after_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='reply',
            name='before_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='생성일시'),
        ),
        migrations.AddField(
            model_name='reply',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='star',
            field=models.IntegerField(default=0, verbose_name='평점'),
        ),
        migrations.AddField(
            model_name='reply',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
