# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeju', '0002_auto_20171028_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='percent',
            field=models.IntegerField(default=0, null=True, verbose_name='할인율'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='가격'),
        ),
    ]
