# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeju', '0003_auto_20171028_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='fcontent',
            field=models.CharField(max_length=1000, verbose_name='음식정보'),
        ),
    ]
