# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeju', '0005_auto_20171029_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='tell',
            field=models.CharField(default='', max_length=20, verbose_name='음식점전화번호'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foods',
            name='where',
            field=models.CharField(max_length=200, verbose_name='음식점위치'),
        ),
    ]
