# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-27 11:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0, verbose_name='발송 시각')),
                ('fname', models.CharField(default='null', max_length=30, verbose_name='음식이름')),
                ('fcontent', models.CharField(max_length=2000, verbose_name='음식정보')),
                ('star', models.IntegerField(default=0, verbose_name='평점')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('where', models.CharField(max_length=50, verbose_name='음식점위치')),
                ('rinfo', models.CharField(default='null', max_length=200, verbose_name='음식점기본정보')),
                ('gps', models.CharField(default='null', max_length=30, verbose_name='gps좌표')),
                ('isdone', models.BooleanField(default=False, verbose_name='낙찰여부')),
                ('file1', models.FileField(upload_to='files/%Y%m%d/')),
                ('file2', models.FileField(upload_to='files/%Y%m%d/')),
                ('file3', models.FileField(upload_to='files/%Y%m%d/')),
                ('file4', models.FileField(upload_to='files/%Y%m%d/')),
                ('file5', models.FileField(upload_to='files/%Y%m%d/')),
                ('issell', models.BooleanField(default=False, verbose_name='응답생성여부')),
                ('regdate', models.DateTimeField(default=datetime.date.today, verbose_name='생성일시')),
                ('startdate', models.DateTimeField(default=datetime.date.today, verbose_name='시작일시')),
                ('enddate', models.DateTimeField(default=datetime.date.today, verbose_name='종료일시')),
                ('usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.date.today, verbose_name='생성일시')),
                ('usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Searchedkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=200, verbose_name='IP주소')),
                ('content', models.CharField(max_length=200, verbose_name='검색내용')),
                ('update', models.DateTimeField(default=datetime.date.today, verbose_name='사용일시')),
                ('usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
