# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171027_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='star',
            field=models.IntegerField(default=0, verbose_name='평점'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='enddate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='종료일시'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='regdate',
            field=models.DateTimeField(auto_now=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='startdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='시작일시'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='searchedkey',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='사용일시'),
        ),
    ]
