# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171028_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporation',
            name='corp_name',
        ),
        migrations.AddField(
            model_name='corporation',
            name='corp_coordinates',
            field=models.CharField(default='null', max_length=50, verbose_name='좌표'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='corp_location',
            field=models.CharField(default='null', max_length=200, verbose_name='가게주소'),
        ),
    ]
