# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171028_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='corp_coordinates',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='corp_descriptioin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='corp_location',
            field=models.TextField(max_length=200),
        ),
    ]
